name: on_the_go_sdk
version: 3.0.0-dev.63
description: OpenAPI Dart client for on-the-go 
homepage: https://aztrix.me

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  dio: '^5.2.0'
  one_of: '>=1.5.0 <2.0.0'
  one_of_serializer: '>=1.5.0 <2.0.0'
  built_value: '>=8.4.0 <9.0.0'
  built_collection: '>=5.1.1 <6.0.0'

dev_dependencies:
  built_value_generator: '>=8.4.0 <9.0.0'
  build_runner: any
  test: ^1.16.0

scripts:
  install: wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/7.9.0/openapi-generator-cli-7.9.0.jar -O openapi-generator-cli.jar 
  generate: java -jar openapi-generator-cli.jar generate -g dart-dio -i openapi.json -o . --skip-validate-spec --additional-properties=pubLibrary=on_the_go_sdk,pubName=on_the_go_sdk --model-name-mappings Response=GenericResponse && sed -i 's/&lt;/</g' lib/src/serializers.dart && sed -i 's/&gt;/>/g' lib/src/serializers.dart && dart run build_runner build && dart fix --apply --code=unused_import --code=unused_element_parameter --code=duplicate_import && dart format .
